version: '3.4'

services:
  cataloguedb:
    image: mongo

  basketdb:
    image: redis:alpine

  portainer:
    image: portainer/portainer-ce

  catalogue.api:
    image: ${DOCKER_REGISTRY-}catalogueapi
    build:
      context: .
      dockerfile: Services/Catalogue/Catalogue.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  mongo_data:
  portainer_data:

